### ISSUE TITLE
Add option to get list of results file

### ISSUE THREAD

**Issue by jpsamper2009** [colcon/colcon-test-result#16]
## Motivation

- It would be nice to have a way to get a list of all the test result files that `colcon test-result` uses, such that the list can be fed into other tools that parse them
- `colcon test-result --all` already gives a list of the XML files with some information about them, so it shouldn't be too hard to add, say, a `--result-files-only` which will print the files only and return with exit code 0
- Our current workaround (which isn't elegant) is to use:

```
(colcon test-result --all || true) | grep xml | cut -d":" -f1
```

## Goal

- Provide a simple way to get a list of test result files

**Comment by dirk-thomas** [comment]
Implemented in #17.
