### ISSUE TITLE
Add --clean option

### ISSUE THREAD

**Issue by jpsamper2009** [colcon/colcon-test-result#22]
## Motivation

- It would be nice to have a shorthand to delete test result files
- With `--result-files-only` option, it is possible to pipe the list of files into `rm`; however, this now produces a warning: e.g.
```
[0.560s] WARNING:colcon.colcon_cmake.test_result.ctest:Skipping 'build/rcutils/Testing/TAG': could not find latest XML file 'build/rcutils/Testing/20190614-2050/Test.xml'
```
- A `--clean` option would take care of cleaning up files like `build/rcutils/Testing/TAG` in additional to the result files

## Acceptance Criteria

- A way to clean up test result files

**Comment by dirk-thomas** [comment]
@jpsamper2009 Please try #29 and colcon/colcon-cmake#50 which adds options to delete all result files.

**Comment by jpsamper2009** [comment]
Thanks!
