### ISSUE TITLE
Full help text isn't available if result dir doesn't exist

### ISSUE THREAD

**Issue by cottsay** [colcon/colcon-test-result#36]
Reproduce by invoking `colcon test-result --help` in an empty directory.

Expected:
<details>

```
$ colcon test-result --help
usage: colcon test-result [-h] [--test-result-base TEST_RESULT_BASE] [--all]
                          [--result-files-only] [--verbose] [--delete]
                          [--delete-yes]

Show the test results generated when testing a set of packages.

optional arguments:
  -h, --help            show this help message and exit
  --test-result-base TEST_RESULT_BASE
                        The base path for all test results (default: build)
  --all                 Show all test result files (even without errors /
                        failures)
  --result-files-only   Print only the paths of the result files. Use with
                        --all to include files without errors / failures
  --verbose             Show additional information for errors / failures
  --delete              Delete all result files. This might include additional
                        files beside what is listed by --result-files-only. An
                        interactive prompt will ask for confirmation
  --delete-yes          Same as --delete without an interactive confirmation
```
</details>

Actual:
<details>

```
$ colcon test-result --help
usage: colcon test-result [-h] [--test-result-base TEST_RESULT_BASE] [--all]
                          [--result-files-only] [--verbose] [--delete]
                          [--delete-yes]
colcon test-result: error: argument --test-result-base: Path 'build' does not exist
```
</details>

**Comment by dirk-thomas** [comment]
The behavior is coming from `argarse`. Another example of this is `colcon test --help --retest-until-fail not-an-int`.

The checking of argument types / validity in `argparse` happens before `--help` is evaluated.

So without dropping the usage of the `type` keyword for arguments (which I don't think is a good idea) I don't think this can be fixed outside of `argparse`.

**Comment by cottsay** [comment]
I think this case differs substantially in that no other arguments are specified. I'm not presenting invalid command line arguments, but the tool thinks I am because of the environment in which it was invoked.

I'm starting to doubt that requiring the directory to exist is a good idea at all. For example, if I call `colcon test-result --delete` and the directory doesn't exist, the return value is non-zero. If it DOES exist but is empty, the return value is zero. Nothing happens either way because there are no test results to delete, but I think the expected behavior of `--delete` would be that a non-zero return value indicates that there were test results that could not be deleted, no?

**Comment by dirk-thomas** [comment]
> I'm not presenting invalid command line arguments

Well, I would disagree on that. The code explicitly requires the argument to be an existing directory:

https://github.com/colcon/colcon-test-result/blob/5c4cc3bc75783a66ef54962fe2fcd2890d1f82e1/colcon_test_result/verb/test_result.py#L27-L29
https://github.com/colcon/colcon-test-result/blob/5c4cc3bc75783a66ef54962fe2fcd2890d1f82e1/colcon_test_result/verb/test_result.py#L111-L116

Maybe that should be changed to not require an existing directory? I am pretty sure the only reason this check was added to prevent user error (give a better error message if the passed dir doesn't exist then to say "no test result found"). The `--delete` option didn't exist at that time.

Please feel free to propose a PR to remove this constraint but try to describe what current behavior / cases are changing and in which way to decide if that has any negative impact.

**Comment by dirk-thomas** [comment]
@cottsay Friendly ping.

If there is no clear proposal what should be done about this I am inclined to close the ticket and keep it as is.

**Comment by cottsay** [comment]
I don't have a proposal, but I did look into the problem.

The situation is far more complex than I thought. As it turns out, `argparse` handles this properly. The type conversions don't happen until all of the actions for all of the arguments have been processed, so the `--help` should be firing before that. There is even a way to make the `--delete*` options succeed even if the directory check would fail, all while preserving the exact existing behavior when none of `--help`, `--delete` or `--delete-yes` are specified. I have all of this working in a sandbox.

The problem is the "fake" parsing happening in colcon-mixin and colcon-defaults. If you uninstall those extensions, you actually get the full `--help` text as expected. The usage error we're seeing is actually bubbling out of one of those supplemental parsings and not the "final" parse.

I tried various methods of suppressing type conversion errors during the supplemental parsing, but the subparsers make this difficult. I thought I had a solution by passing a `Namespace` into `parse_known_args`, but the subparsers generate a new one for their use and then merge the namespaces when they're done. So that didn't work.

At this point, I think it's just too much work. I don't know how to replicate what colcon-mixin and colcon-defaults are doing without running argparse over the arguments list with "help" suppressed like is currently happening. But it is unfortunate that argparse is behaving differently when certain extensions are present.

**Comment by dirk-thomas** [comment]
> If you uninstall those extensions, you actually get the full `--help` text as expected.

That certainly sounds like it should be fixable in `colcon` then...

> The problem is the "fake" parsing happening in colcon-mixin and colcon-defaults.

Can you clarify what you mean with "fake" parsing? `parse_known_args`?

**Comment by cottsay** [comment]
> Can you clarify what you mean with "fake" parsing? `parse_known_args`?

Yes. Parsing the arguments in one of the `parse_args` wrappers for use in the local context without actually returning the results.

https://github.com/colcon/colcon-defaults/blob/fc4f2f1e45b78fe212d41690520d9be68fca6cae/colcon_defaults/argument_parser/defaults.py#L103-L105

https://github.com/colcon/colcon-mixin/blob/5144432c087705bfcc6454052b43e54bc2fba0c4/colcon_mixin/mixin/mixin_argument.py#L135-L136

**Comment by dirk-thomas** [comment]
> ... without actually returning the results.

Both cases do return the parsed args later in the function:

* https://github.com/colcon/colcon-defaults/blob/fc4f2f1e45b78fe212d41690520d9be68fca6cae/colcon_defaults/argument_parser/defaults.py#L129
* https://github.com/colcon/colcon-mixin/blob/5144432c087705bfcc6454052b43e54bc2fba0c4/colcon_mixin/mixin/mixin_argument.py#L146-L168

**Comment by cottsay** [comment]
> > ... without actually returning the results.
> 
> Both cases do return the parsed args later in the function:

When running normally they do, but when this behavior surfaces, execution never reaches the points you linked. The error comes out of the intermediate call to `parse_known_args` earlier in those functions.

Normally, when the `--help` argument is encountered, it triggers the help text and exits immediately. However, that behavior is suppressed when those calls are made to `parse_known_args` and the parsing continues. Eventually the type conversions are executed after all of the actions have been processed, and the type conversion for `test_results_base` raises. Execution never would have made it that far had the `--help` behavior not been suppressed. That's why the behavior is different when those two plugins are present.

**Comment by dirk-thomas** [comment]
The problem is that a full help message can't be printed at this point in time because the complete argument parser tree hasn't been constructed yet. The known args need to be parsed in order to determine how to populate the selected subtree. And it seems `argparse` can't parse known args if one of the existing args fails the `type` callback (which makes kind of sense).

> if I call `colcon test-result --delete` and the directory doesn't exist, the return value is non-zero. If it DOES exist but is empty, the return value is zero. Nothing happens either way because there are no test results to delete.

I disagree with the assumption that both cases are equal and should return zero. If you call `rm filename-which-doesnt-exist` it will return a non-zero code because what the user requested can't be satisfied (even if the end state is the same - after the invocation the passed filename doesn't exist). So I still think that passing a not-existing directory should return in an error.

> I think the expected behavior of `--delete` would be that a non-zero return value indicates that there were test results that could not be deleted, no?

Sure, I assume that is already the case.

---

So I unfortunately don't see a way how to improve this while the check happens in the `type` callback.

Maybe moving the check outside of the argument parsing and instead check it after the arguments have been passed (and still return non-zero) is an acceptable workaround? Please see #37 for this.

**Comment by cottsay** [comment]
> If you call `rm filename-which-doesnt-exist` it will return a non-zero code because what the user requested can't be satisfied

I don't think this is an entirely fair comparison because both `--delete` and `--delete-yes` are idempotent, where `rm` is not, and this makes their behavior more akin to `rm -f` (especially so for `--delete-yes`).

Honestly, I'm not interested in discussing this further. As a seasoned Linux user, I find this behavior unexpected, but certainly not unacceptable. Clearly you disagree, and that's OK. Thank you for the diverse perspective on this matter - I think we should table it for now.

---

> So I unfortunately don't see a way how to improve this while the check happens in the type callback.

I have an idea how we might be able to suppress the type conversions, but I'm not sure where the code should live because we need to solve this issue in both colcon-defaults and colcon-mixin. Please take a look at this commit and let me know where you think it could be integrated: https://github.com/colcon/colcon-defaults/commit/6630d87793e82d3781d124b39d67a373392be4b6

#37 is an improvement, in my opinion; and could be merged even if we can't arrive at another solution.

**Comment by mateus-amarante** [comment]
I just want to add that I think this bug is related to the problem I'm facing: the `test-result-base` default folder is not overridden by `COLCON_DEFAULTS_FILE`. The `argparse` type is evaluated against the default value, which is fixed as "build".

**Comment by dirk-thomas** [comment]
> the `test-result-base` default folder is not overridden by `COLCON_DEFAULTS_FILE`

@mateus-amarante Can you please share your `default.yaml`, reproducible steps as well as a description of the expected and actual behavior?

**Comment by mateus-amarante** [comment]
@dirk-thomas First, thanks for the quick reply! It follows the configuration:
```yaml
{
  "test": {
    "test-result-base": "/path/to/test-result",
  },
  "test-result": {
    "test-result-base": "/path/to/test-result",
  },
}
```
When I run `colcon test` from any folder the test results are placed in the specified folder. However, when I run `colcon test-result` without a "build" folder inside, I get the following error:
```
usage: colcon test-result [-h] [--test-result-base TEST_RESULT_BASE] [--all]
                          [--result-files-only] [--verbose] [--delete]
                          [--delete-yes] [--mixin-files [FILE [FILE ...]]]
                          [--mixin [mixin1 [mixin2 ...]]]
colcon test-result: error: argument --test-result-base: Path 'build' does not exist
```

When there is a "build" subfolder, the results are placed there instead of the specified default folder.

When I run `colcon test-result --test-result-base /path/to/test-result`, I get the expected output.

**Comment by mateus-amarante** [comment]
I think #36 might be related to the problem I'm facing because both regards the `--test-result-base` arg parsing. I can create a separate issue if you think it is more adequate.

**Comment by cottsay** [comment]
Alright, I opened three PRs to fix this:
* colcon/colcon-core#416
* colcon/colcon-defaults#28
* colcon/colcon-mixin#30

@mateus-amarante, if you're able, please give them a shot (you don't need the `colcon-mixin` one if you don't have `colcon-mixin` installed). I believe that this should delay the type conversion for `--test-result-base` until after `colcon-defaults` has updated the value.

**Comment by mateus-amarante** [comment]
@cottsay I installed `colcon` from source with the branches you listed and did the same test I described in https://github.com/colcon/colcon-test-result/issues/36#issuecomment-732851901. It worked as I expected! `colcon test-result --help` works too!

Great job!

**Comment by alsora** [comment]
Hi, any update on the issue about `defaults.yaml` being ignored?
It looks like it's still broken in  ROS galactic

**Comment by cottsay** [comment]
This should be resolved with recent releases of colcon-core, colcon-defaults, and colcon-mixin.
